# Doctrine JSON ODM Bundle Configuration
doctrine_json_odm:
    # Choose the serializer to use: symfony or vuryss
    # - symfony: Maximum compatibility with existing Symfony projects
    # - vuryss: Maximum performance for modern PHP applications
    serializer: symfony

    # Enable lazy loading for JSON documents
    # When true, objects are not deserialized until first property access
    lazy_loading: true

    # Lazy loading strategy: ghost or proxy
    # - ghost: In-place initialization (more memory efficient)
    # - proxy: Proxy to real instance (better for complex inheritance)
    lazy_strategy: ghost

    # Map class names to type aliases for storage optimization
    # This reduces JSON size by using short aliases instead of full class names
    type_map:
        # Alias: Full Class Name
        user: 'App\Entity\User'
        product: 'App\Entity\Product'
        order: 'App\Entity\Order'
        category: 'App\Entity\Category'
        # Add more mappings as needed

    # Default serialization context
    # These options are passed to the serializer during serialization
    serialization_context:
        groups: ['api', 'export']
        # datetime_format: 'Y-m-d H:i:s'
        # circular_reference_limit: 1

    # Default deserialization context
    # These options are passed to the serializer during deserialization
    deserialization_context:
        groups: ['api', 'import']
        # allow_extra_attributes: false

    # Symfony serializer specific configuration
    symfony_serializer:
        # Custom normalizers to register (service IDs)
        normalizers: []
            # - 'app.custom_normalizer'

        # Custom denormalizers to register (service IDs)
        denormalizers: []
            # - 'app.custom_denormalizer'

        # Custom encoders to register (service IDs)
        encoders: []
            # - 'app.custom_encoder'

    # Vuryss serializer specific configuration
    vuryss_serializer:
        # Custom normalizers to register (service IDs)
        normalizers: []
            # - 'app.custom_normalizer'

        # Custom denormalizers to register (service IDs)
        denormalizers: []
            # - 'app.custom_denormalizer'

        # Enable metadata caching for better performance
        enable_cache: true
