name: Continuous Integration

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    quality:
        name: Quality (PHP 8.5 / Symfony 8 latest)
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Set up PHP 8.5
                uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
                with:
                    extensions: mbstring, xml, ctype, iconv, json
                    tools: composer:v2
                    php-version: 8.5

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Install latest dependencies
                run: composer update --no-interaction --no-progress --prefer-dist

            -   name: Security check
                run: composer audit

            -   name: Check coding standards
                run: vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no

            -   name: PHP linting
                run: composer run-script lint:php

            -   name: Static code analysis
                run: vendor/bin/phpstan analyse --memory-limit=1G -v

            -   name: Run tests
                run: vendor/bin/pest

            -   name: Check workflow files
                run: |
                    bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
                    ./actionlint -color
                shell: bash

    tests:
        name: Tests (${{ matrix.dependencies.name }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                dependencies:
                    -   name: Symfony 7.4 minimum
                        composer-flags: --no-interaction --no-progress --prefer-dist --prefer-lowest --prefer-stable
                    -   name: Symfony 8 latest
                        composer-flags: --no-interaction --no-progress --prefer-dist

        steps:
            -   name: Checkout code
                uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            -   name: Set up PHP 8.5
                uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
                with:
                    extensions: mbstring, xml, ctype, iconv, json
                    tools: composer:v2
                    php-version: 8.5

            -   name: Install dependencies
                run: composer update ${{ matrix.dependencies.composer-flags }}

            -   name: Run tests
                run: vendor/bin/pest
